using System.Data;
using CorchEdges.Data.Abstractions;

namespace CorchEdges.Tests.Infrastructure;

public static class DataTableTestHelper
{
    /// <summary>
    /// Creates a DataTable structure based on an entity configuration's metadata.
    /// This ensures tests always use a schema that passes the StrictSchemaDetector.
    /// </summary>
    public static DataTable CreateDataTableFromConfiguration(IEntityTypeMetaInfo config)
    {
        var table = new DataTable(config.SheetName);
        var metadata = config.GetColumnMetadata();

        foreach (var column in metadata)
        {
            // Identity/Primary Keys are usually auto-generated by the DB and 
            // not present in the source Excel file.
            if (column.IsKey && column.UseIdentityColumn) continue;
            
            // Excel source columns are treated as strings before normalization.
            table.Columns.Add(column.ColumnName, typeof(string));
        }

        return table;
    }
}
