using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Attributes;
using System.ComponentModel.DataAnnotations;

namespace CorchEdges.Models.Requests;

/// <summary>
/// Represents the response returned after webhook registration or operations.
/// Contains information about the webhook subscription including its configuration and status.
/// </summary>
/// <param name="Message">A descriptive message about the webhook operation result</param>
/// <param name="SubscriptionId">The unique identifier of the Microsoft Graph subscription</param>
/// <param name="ExpirationDateTime">The UTC date and time when this webhook subscription will expire</param>
/// <param name="CallbackUrl">The HTTPS URL that will receive webhook notifications</param>
/// <param name="Resource">The Microsoft Graph resource path being monitored</param>
/// <param name="ChangeType">The type of changes this webhook will notify about</param>
/// <param name="ClientState">Client-defined state value used for webhook validation</param>
public record WebhookResponse(
    [property: OpenApiProperty(Description = "Human-readable message describing the result of the webhook operation")]
    [property: Required]
    string Message,
    
    [property: OpenApiProperty(Description = "Unique subscription ID generated by Microsoft Graph for this webhook")]
    [property: Required]
    string SubscriptionId,
    
    [property: OpenApiProperty(Description = "UTC expiration date/time of the webhook subscription. Null if subscription failed to create.")]
    DateTimeOffset? ExpirationDateTime,
    
    [property: OpenApiProperty(Description = "The callback URL configured for receiving webhook notifications")]
    [property: Required]
    [property: Url]
    string CallbackUrl,
    
    [property: OpenApiProperty(Description = "Microsoft Graph resource path being monitored")]
    [property: Required]
    string Resource,
    
    [property: OpenApiProperty(Description = "Type of changes being monitored (typically 'updated' for SharePoint lists)")]
    [property: Required]
    string ChangeType,
    
    [property: OpenApiProperty(Description = "Client-defined state value included in webhook notifications for validation")]
    [property: Required]
    string ClientState)
{
    public override string ToString()
    {
        return $"{{ Message = {Message}, SubscriptionId = {SubscriptionId}, ExpirationDateTime = {ExpirationDateTime}, CallbackUrl = {CallbackUrl}, Resource = {Resource}, ChangeType = {ChangeType}, ClientState = {ClientState} }}";
    }
}