using Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Attributes;
using System.ComponentModel.DataAnnotations;

namespace CorchEdges.Models.Requests;

/// <summary>
/// Represents the response returned after webhook registration or operations.
/// Contains information about the webhook subscription including its configuration and status.
/// </summary>
public record WebhookResponse(
    /// <summary>
    /// A descriptive message about the webhook operation result.
    /// </summary>
    /// <example>Webhook successfully registered for SharePoint list</example>
    [property: OpenApiProperty(Description = "Human-readable message describing the result of the webhook operation")]
    [property: Required]
    string Message,
    
    /// <summary>
    /// The unique identifier of the Microsoft Graph subscription created for this webhook.
    /// </summary>
    /// <example>7f103c7d-6014-4fb5-a52c-2b1f7e8a9b3e</example>
    [property: OpenApiProperty(Description = "Unique subscription ID generated by Microsoft Graph for this webhook")]
    [property: Required]
    string SubscriptionId,
    
    /// <summary>
    /// The UTC date and time when this webhook subscription will expire.
    /// </summary>
    /// <example>2024-08-01T14:30:00.000Z</example>
    [property: OpenApiProperty(Description = "UTC expiration date/time of the webhook subscription. Null if subscription failed to create.")]
    DateTimeOffset? ExpirationDateTime,
    
    /// <summary>
    /// The HTTPS URL that will receive webhook notifications from Microsoft Graph.
    /// </summary>
    /// <example>https://your-app.azurewebsites.net/sharepoint/webhook?code=your-function-key</example>
    [property: OpenApiProperty(Description = "The callback URL configured for receiving webhook notifications")]
    [property: Required]
    [property: Url]
    string CallbackUrl,
    
    /// <summary>
    /// The Microsoft Graph resource path being monitored by this webhook.
    /// </summary>
    /// <example>sites/12345678-1234-1234-1234-123456789012/lists/87654321-4321-4321-4321-210987654321</example>
    [property: OpenApiProperty(Description = "Microsoft Graph resource path (e.g., 'sites/{siteId}/lists/{listId}') being monitored")]
    [property: Required]
    string Resource,
    
    /// <summary>
    /// The type of changes this webhook will notify about.
    /// </summary>
    /// <example>updated</example>
    [property: OpenApiProperty(Description = "Type of changes being monitored (typically 'updated' for SharePoint lists)")]
    [property: Required]
    string ChangeType,
    
    /// <summary>
    /// Client-defined state value used for webhook validation and correlation.
    /// </summary>
    /// <example>client-state-abc123</example>
    [property: OpenApiProperty(Description = "Client-defined state value included in webhook notifications for validation")]
    [property: Required]
    string ClientState)
{
    /// <summary>
    /// Returns a formatted string representation of the webhook response.
    /// </summary>
    /// <returns>A string containing all webhook response properties.</returns>
    public override string ToString()
    {
        return $"{{ Message = {Message}, SubscriptionId = {SubscriptionId}, ExpirationDateTime = {ExpirationDateTime}, CallbackUrl = {CallbackUrl}, Resource = {Resource}, ChangeType = {ChangeType}, ClientState = {ClientState} }}";
    }
}